### ISSUE TITLE
app/style/style.css is missing

### ISSUE THREAD

**Issue by jumpmanjay** [demonrik/HDHR-DVRUI#1]
Getting error: 

`Warning: file_put_contents(./style/style.css): failed to open stream: Permission denied in /volume7/web/hdhr/tools/lessc.inc.php on line 1835`

The file is missing.

**Comment by avandeputte** [comment]
That file is generated on the fly the first time you run the application.  You're getting a permission denied creating that file.

Make sure the folder is writeable by the webserver.  Ideally you do that by setting the ownership of the folders to the web server username, however you can also chmod 777 the folder if you're so inclined

**Comment by jumpmanjay** [comment]
Worked like a charm. Thanks!
