### ISSUE TITLE
Missing style.css?

### ISSUE THREAD

**Issue by hkarpf** [demonrik/HDHR-DVRUI#2]
![image](https://cloud.githubusercontent.com/assets/10375411/17753845/55c2d632-6497-11e6-9792-f5962a638fa3.png)

Cloned git repo and it appears as though there's a missing style.css.  Maybe that's a builtin file to the QNAP DVR?

**Comment by avandeputte** [comment]
style.css is generated on the fly the first time you run the app.
Make sure your style folder is writeable by the web server user.

**Comment by hkarpf** [comment]
Changing file perms fixed this right up, thank you!
