### ISSUE TITLE
docker image

### ISSUE THREAD

**Issue by avandeputte** [demonrik/HDHR-DVRUI#3]
I saw the request for docker on the forum,  I tried to respond there but it seems their cloudflare thing is blocking me now.   Well,  docker is something I've been playing with quite a bit recently.   So I decided to give it a try :)

The dockerfile for this is very trivial.   You just need to build on the official php-apache image.   

```
FROM php:7.2-apache

# Use the default production configuration
RUN mv "$PHP_INI_DIR/php.ini-production" "$PHP_INI_DIR/php.ini"
RUN apt-get update && apt-get install -y git
WORKDIR /tmp

RUN git clone https://github.com/demonrik/HDHR-DVRUI.git /tmp &&  \
     rm -Rf /var/www/html/* && \
     cp -Rf /tmp/app/* /var/www/html && \
     chmod 777 /var/www/html/themes/default && \
     rm -Rf /tmp/app

```

The built image is here:  https://hub.docker.com/r/avandeputte/hdhr-dvrui

feel free to take ownership of the dockerfile and make it official, I am not back :)

**Comment by demonrik** [comment]
good to hear from you @avandeputte 
been lonely here - none have stepped in to fill the vacuum you left :(
thanks for the info

**Comment by wowsher** [comment]
I apologize if this is considered necroing but since it is an issue I figured it was fair game... :) I followed the link above but that was a much older version of the application so I created an updated docker that pulled 0.8.6 it can be found here:  https://hub.docker.com/r/wowsher/hdhr-dvrui.

**Comment by klishb** [comment]
> I apologize if this is considered necroing but since it is an issue I figured it was fair game... :) I followed the link above but that was a much older version of the application so I created an updated docker that pulled 0.8.6 it can be found here: https://hub.docker.com/r/wowsher/hdhr-dvrui.

@wowsher I just installed your container, but it won't start for me.  Is there any necessary configuration or prerequisites that I'm missing?

**Comment by wowsher** [comment]
@klishb it has been a while however I just verified that the only thing you need to do if you run in network bridge mode is map port 80 from the container to the outside network port.  In my case I just use 80:80 but you can also use that to map to a different port if you need to.

**Comment by klishb** [comment]
Ah bridge mode was the key.  I had it in host mode.  Thanks!

**Comment by demonrik** [comment]
This project is EOL
At some point this is going to stop working as Silicondust have made a number of changes to the API and are only supporting the legacy that is used here until end of year.
