### ISSUE TITLE
Web Port Designation in "qpkg.conf" breaks add-on for NAS custom web ports

### ISSUE THREAD

**Issue by gibxxi** [demonrik/HDHR-DVRUI#5]
This addon creates the following line in the /etc/config/qpkg.conf file (/mnt/HDA_ROOT/.config/qpkg.conf):

Web_Port = 80

If the user's NAS should then be running the default Web Server (HTTP/HTTPS) on differing ports than the default, the app will be using an incorrect link from QTS and the app will fail to load in the web browser.

I notice your HDHomeRunDVR Manager add-on, which resides right above this one in the qpkg.conf file does not have this line by default.

In any case, removing the offending line and re-saving the qpkg.conf file (via SSH) solves the issue. The app is launched from QTS and uses whatever the currently set parameters are for the Web Server, and the app loads successfully.

**Comment by demonrik** [comment]
Thanks - have made the change and will be in next build
