### ISSUE TITLE
Not processing null StartPadding and EndPadding

### ISSUE THREAD

**Issue by blainebauer** [demonrik/HDHR-DVRUI#6]
I'm getting errors in my Apache log like this for start and end padding:
[Sun Aug 18 12:01:49.877390 2019] [:error] [pid 16801] [client 192.168.1.52:64272] PHP Notice:  Undefined index: EndPadding in /var/www/html/includes/dvrui_rules.php on line 87, referer: http://192.168.1.21/index.php

The recording_rules API is not returning these key:value pairs if they are set to "On Time." 

I added some checking for these starting on line 86 of dvrui_rules.php:

               if (isset($rule[$this->recording_StartPad])) {
                        $startPad = $rule[$this->recording_StartPad];
                }
                else {
                        $startPad = 0;
                }
                if (isset($rule[$this->recording_EndPad])) {
                        $endPad = $rule[$this->recording_EndPad];
                }
                else {
                        $endPad = 0;
                }

**Comment by demonrik** [comment]
Fixed in the repo for the next release.
the right way to do this is check for the key in the returned response,
i.e. 		if (array_key_exists($this->recording_StartPad,$rule)) {...}
